name: Enviar resumen folclore RCA diario

on:
  schedule:
    - cron: '0 12 * * *'  # 9:00 AM hora Argentina (UTC-3)
  workflow_dispatch:

jobs:
  enviar_resumen:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install requests

      - name: Ejecutar bot
        run: python telegram_bot_daily.py
