name: Ejecutar bot diario

on:
  schedule:
    - cron: '0 12 * * *' # 9:00 AM Argentina (UTC-3 corresponde a 12:00 UTC)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repo
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: pip install requests

      - name: Ejecutar bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python telegram_bot_daily.py
